name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get node version from nvm
        run: nvmrc=$(cat .nvmrc)
        
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${nvmrc}
          cache: 'npm'

      - name: Clean install dependencies
        run: npm ci

      - name: Lint & format check
        run: npm run lint

      - name: Run unit tests
        run: npm run test
